version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: superpwd
      MYSQL_DATABASE: library
      MYSQL_USER: nicolas
      MYSQL_PASSWORD: nikospwd
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

#  java-app:
#    build: ./api/my-library
#    container_name: java-app
#    ports:
#       - "8080:8080"
#    depends_on:
#      mysql:
#        condition: service_healthy

#  frontend:
#    build: ./front/my-library
#    container_name: angular-frontend
#     ports:
#      - "4000:4000"
#    depends_on:
#      - java-app
